// @generated
// This file is automatically generated by Kanel. Do not modify manually.

<<<<<<< HEAD
import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type default as Action } from "./Action";
import { type StagesId } from "./Stages";
=======
import { type ActionsId } from './Actions';
import { type StagesId } from './Stages';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
>>>>>>> a0252e8 (add schma and server actions)

/** Identifier type for public.action_instances */
export type ActionInstancesId = string & { __brand: 'ActionInstancesId' };

/** Represents the table public.action_instances */
export default interface ActionInstancesTable {
<<<<<<< HEAD
	id: ColumnType<ActionInstancesId, ActionInstancesId | undefined, ActionInstancesId>;
=======
  id: ColumnType<ActionInstancesId, ActionInstancesId, ActionInstancesId>;

  action_id: ColumnType<ActionsId, ActionsId, ActionsId>;
>>>>>>> a0252e8 (add schma and server actions)

  stage_id: ColumnType<StagesId, StagesId, StagesId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

<<<<<<< HEAD
	updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

	config: ColumnType<unknown | null, unknown | null, unknown | null>;

	name: ColumnType<string, string | undefined, string>;

	action: ColumnType<Action, Action, Action>;
=======
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
>>>>>>> a0252e8 (add schma and server actions)
}

export type ActionInstances = Selectable<ActionInstancesTable>;

export type NewActionInstances = Insertable<ActionInstancesTable>;

export type ActionInstancesUpdate = Updateable<ActionInstancesTable>;
