// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type ActionInstancesId } from "./ActionInstances";
import { type default as ActionRunStatus } from "./ActionRunStatus";
import { type default as Event } from "./Event";
import { type PubsId } from "./Pubs";

/** Identifier type for public.action_runs */
export type ActionRunsId = string & { __brand: "ActionRunsId" };

/** Represents the table public.action_runs */
export default interface ActionRunsTable {
	id: ColumnType<ActionRunsId, ActionRunsId | undefined, ActionRunsId>;

	action_instance_id: ColumnType<ActionInstancesId, ActionInstancesId, ActionInstancesId>;

	config: ColumnType<unknown | null, unknown | null, unknown | null>;

	event: ColumnType<Event | null, Event | null, Event | null>;

	params: ColumnType<unknown | null, unknown | null, unknown | null>;

	status: ColumnType<ActionRunStatus, ActionRunStatus, ActionRunStatus>;

	created_at: ColumnType<Date, Date | string | undefined, Date | string>;

	updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

	pub_id: ColumnType<PubsId, PubsId, PubsId>;
}

export type ActionRuns = Selectable<ActionRunsTable>;

export type NewActionRuns = Insertable<ActionRunsTable>;

export type ActionRunsUpdate = Updateable<ActionRunsTable>;
