// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ActionsId } from './Actions';
import { type PubFieldsId } from './PubFields';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public._ActionToPubField */
export default interface ActionToPubFieldTable {
  A: ColumnType<ActionsId, ActionsId, ActionsId>;

  B: ColumnType<PubFieldsId, PubFieldsId, PubFieldsId>;
}

export type ActionToPubField = Selectable<ActionToPubFieldTable>;

export type NewActionToPubField = Insertable<ActionToPubFieldTable>;

export type ActionToPubFieldUpdate = Updateable<ActionToPubFieldTable>;
