// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.Action */
enum Action {
	log = "log",
	pdf = "pdf",
	email = "email",
	pushToV6 = "pushToV6",
	move = "move",
	http = "http",
}

export default Action;
