// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.ActionRunStatus */
enum ActionRunStatus {
	success = "success",
	failure = "failure",
}

export default ActionRunStatus;
