// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type StagesId } from './Stages';
import { type PubsId } from './Pubs';
import { type UsersId } from './Users';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.action_move */
export type ActionMoveId = string & { __brand: 'ActionMoveId' };

/** Represents the table public.action_move */
export default interface ActionMoveTable {
<<<<<<< HEAD
	id: ColumnType<ActionMoveId, ActionMoveId | undefined, ActionMoveId>;
=======
  id: ColumnType<ActionMoveId, ActionMoveId, ActionMoveId>;
>>>>>>> a0252e8 (add schma and server actions)

  source_stage_id: ColumnType<StagesId, StagesId, StagesId>;

  destination_stage_id: ColumnType<StagesId, StagesId, StagesId>;

  pub_id: ColumnType<PubsId, PubsId, PubsId>;

  user_id: ColumnType<UsersId, UsersId, UsersId>;

  note: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ActionMove = Selectable<ActionMoveTable>;

export type NewActionMove = Insertable<ActionMoveTable>;

export type ActionMoveUpdate = Updateable<ActionMoveTable>;
