// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.actions */
export type ActionsId = string & { __brand: 'ActionsId' };

/** Represents the table public.actions */
export default interface ActionsTable {
  id: ColumnType<ActionsId, ActionsId, ActionsId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  description: ColumnType<string, string | undefined, string>;
}

export type Actions = Selectable<ActionsTable>;

export type NewActions = Insertable<ActionsTable>;

export type ActionsUpdate = Updateable<ActionsTable>;
