// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type ActionInstancesId } from "./ActionInstances";
import { type default as ActionRunStatus } from "./ActionRunStatus";
import { type default as Event } from "./Event";
import { type PubsId } from "./Pubs";
import { type UsersId } from "./Users";

/** Identifier type for public.action_runs */
export type ActionRunsId = string & { __brand: "ActionRunsId" };

/** Represents the table public.action_runs */
export default interface ActionRunsTable {
	id: ColumnType<ActionRunsId, ActionRunsId | undefined, ActionRunsId>;

	actionInstanceId: ColumnType<
		ActionInstancesId | null,
		ActionInstancesId | null,
		ActionInstancesId | null
	>;

	pubId: ColumnType<PubsId | null, PubsId | null, PubsId | null>;

	config: ColumnType<unknown | null, unknown | null, unknown | null>;

	event: ColumnType<Event | null, Event | null, Event | null>;

	params: ColumnType<unknown | null, unknown | null, unknown | null>;

	status: ColumnType<ActionRunStatus, ActionRunStatus, ActionRunStatus>;

	userId: ColumnType<UsersId | null, UsersId | null, UsersId | null>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

	result: ColumnType<unknown, unknown, unknown>;
}

export type ActionRuns = Selectable<ActionRunsTable>;

export type NewActionRuns = Insertable<ActionRunsTable>;

export type ActionRunsUpdate = Updateable<ActionRunsTable>;
