// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.ApiAccessScope */
enum ApiAccessScope {
	community = "community",
	pub = "pub",
	stage = "stage",
	member = "member",
	pubType = "pubType",
}

export default ApiAccessScope;
