// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type ApiAccessTokensId } from "./ApiAccessTokens";

/** Identifier type for public.api_access_logs */
export type ApiAccessLogsId = string & { __brand: "ApiAccessLogsId" };

/** Represents the table public.api_access_logs */
export default interface ApiAccessLogsTable {
	id: ColumnType<ApiAccessLogsId, ApiAccessLogsId | undefined, ApiAccessLogsId>;

	accessTokenId: ColumnType<ApiAccessTokensId, ApiAccessTokensId, ApiAccessTokensId>;

	timestamp: ColumnType<Date, Date | string | undefined, Date | string>;

	action: ColumnType<string, string, string>;
}

export type ApiAccessLogs = Selectable<ApiAccessLogsTable>;

export type NewApiAccessLogs = Insertable<ApiAccessLogsTable>;

export type ApiAccessLogsUpdate = Updateable<ApiAccessLogsTable>;
