// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.ApiAccessType */
enum ApiAccessType {
	read = "read",
	write = "write",
	archive = "archive",
}

export default ApiAccessType;
