// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type CommunitiesId } from "./Communities";
import { type UsersId } from "./Users";

/** Identifier type for public.api_access_tokens */
export type ApiAccessTokensId = string & { __brand: "ApiAccessTokensId" };

/** Represents the table public.api_access_tokens */
export default interface ApiAccessTokensTable {
	id: ColumnType<ApiAccessTokensId, ApiAccessTokensId | undefined, ApiAccessTokensId>;

	token: ColumnType<string, string, string>;

	name: ColumnType<string, string, string>;

	description: ColumnType<string | null, string | null, string | null>;

	communityId: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>;

	expiration: ColumnType<Date, Date | string, Date | string>;

	revoked: ColumnType<boolean, boolean | undefined, boolean>;

	issuedById: ColumnType<UsersId, UsersId, UsersId>;

	issuedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ApiAccessTokens = Selectable<ApiAccessTokensTable>;

export type NewApiAccessTokens = Insertable<ApiAccessTokensTable>;

export type ApiAccessTokensUpdate = Updateable<ApiAccessTokensTable>;
