// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type UsersId } from "./Users";

/** Identifier type for public.auth_tokens */
export type AuthTokensId = string & { __brand: "AuthTokensId" };

/** Represents the table public.auth_tokens */
export default interface AuthTokensTable {
	id: ColumnType<AuthTokensId, AuthTokensId, AuthTokensId>;

	hash: ColumnType<string, string, string>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	expiresAt: ColumnType<Date, Date | string, Date | string>;

	isUsed: ColumnType<boolean, boolean | undefined, boolean>;

	userId: ColumnType<UsersId, UsersId, UsersId>;
}

export type AuthTokens = Selectable<AuthTokensTable>;

export type NewAuthTokens = Insertable<AuthTokensTable>;

export type AuthTokensUpdate = Updateable<AuthTokensTable>;
