// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.CoreSchemaType */
enum CoreSchemaType {
	String = "String",
	Boolean = "Boolean",
	Vector3 = "Vector3",
	DateTime = "DateTime",
	Email = "Email",
	URL = "URL",
	UserId = "UserId",
	FileUpload = "FileUpload",
}

export default CoreSchemaType;
