// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.Event */
enum Event {
	pubEnteredStage = "pubEnteredStage",
	pubLeftStage = "pubLeftStage",
}

export default Event;
