// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.integrations */
export type IntegrationsId = string & { __brand: 'IntegrationsId' };

/** Represents the table public.integrations */
export default interface IntegrationsTable {
<<<<<<< HEAD
	id: ColumnType<IntegrationsId, IntegrationsId | undefined, IntegrationsId>;
=======
  id: ColumnType<IntegrationsId, IntegrationsId, IntegrationsId>;
>>>>>>> a0252e8 (add schma and server actions)

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  actions: ColumnType<unknown, unknown, unknown>;

  name: ColumnType<string, string, string>;

  settingsUrl: ColumnType<string, string, string>;
}

export type Integrations = Selectable<IntegrationsTable>;

export type NewIntegrations = Insertable<IntegrationsTable>;

export type IntegrationsUpdate = Updateable<IntegrationsTable>;
