// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type IntegrationInstancesId } from './IntegrationInstances';
import { type PubsId } from './Pubs';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public._IntegrationInstanceToPub */
export default interface IntegrationInstanceToPubTable {
  A: ColumnType<IntegrationInstancesId, IntegrationInstancesId, IntegrationInstancesId>;

  B: ColumnType<PubsId, PubsId, PubsId>;
}

export type IntegrationInstanceToPub = Selectable<IntegrationInstanceToPubTable>;

export type NewIntegrationInstanceToPub = Insertable<IntegrationInstanceToPubTable>;

export type IntegrationInstanceToPubUpdate = Updateable<IntegrationInstanceToPubTable>;
