// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

/** Identifier type for public.integrations */
export type IntegrationsId = string & { __brand: "IntegrationsId" };

/** Represents the table public.integrations */
export default interface IntegrationsTable {
	id: ColumnType<IntegrationsId, IntegrationsId | undefined, IntegrationsId>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

	actions: ColumnType<unknown, unknown, unknown>;

	name: ColumnType<string, string, string>;

	settingsUrl: ColumnType<string, string, string>;
}

export type Integrations = Selectable<IntegrationsTable>;

export type NewIntegrations = Insertable<IntegrationsTable>;

export type IntegrationsUpdate = Updateable<IntegrationsTable>;
