// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CommunitiesId } from "./Communities";
import { type ColumnType, type Selectable, type Insertable, type Updateable } from "kysely";

/** Identifier type for public.member_groups */
export type MemberGroupsId = string & { __brand: "MemberGroupsId" };

/** Represents the table public.member_groups */
export default interface MemberGroupsTable {
	id: ColumnType<MemberGroupsId, MemberGroupsId, MemberGroupsId>;

	created_at: ColumnType<Date, Date | string | undefined, Date | string>;

	updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

	canAdmin: ColumnType<boolean, boolean, boolean>;

	community_id: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>;
}

export type MemberGroups = Selectable<MemberGroupsTable>;

export type NewMemberGroups = Insertable<MemberGroupsTable>;

export type MemberGroupsUpdate = Updateable<MemberGroupsTable>;
