// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.MemberRole */
enum MemberRole {
	admin = "admin",
	editor = "editor",
	contributor = "contributor",
}

export default MemberRole;
