// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type StagesId } from './Stages';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.move_constraint */
export type MoveConstraintId = string & { __brand: 'MoveConstraintId' };

/** Represents the table public.move_constraint */
export default interface MoveConstraintTable {
  id: ColumnType<MoveConstraintId, MoveConstraintId, MoveConstraintId>;

  stage_id: ColumnType<StagesId, StagesId, StagesId>;

  destination_id: ColumnType<StagesId, StagesId, StagesId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MoveConstraint = Selectable<MoveConstraintTable>;

export type NewMoveConstraint = Insertable<MoveConstraintTable>;

export type MoveConstraintUpdate = Updateable<MoveConstraintTable>;
