// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type MembersId } from './Members';
import { type MemberGroupsId } from './MemberGroups';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.permissions */
export type PermissionsId = string & { __brand: 'PermissionsId' };

/** Represents the table public.permissions */
export default interface PermissionsTable {
<<<<<<< HEAD
	id: ColumnType<PermissionsId, PermissionsId | undefined, PermissionsId>;
=======
  id: ColumnType<PermissionsId, PermissionsId, PermissionsId>;
>>>>>>> a0252e8 (add schma and server actions)

  member_id: ColumnType<MembersId | null, MembersId | null, MembersId | null>;

  member_group_id: ColumnType<MemberGroupsId | null, MemberGroupsId | null, MemberGroupsId | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Permissions = Selectable<PermissionsTable>;

export type NewPermissions = Insertable<PermissionsTable>;

export type PermissionsUpdate = Updateable<PermissionsTable>;
