// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type MemberGroupsId } from "./MemberGroups";
import { type MembersId } from "./Members";

/** Identifier type for public.permissions */
export type PermissionsId = string & { __brand: "PermissionsId" };

/** Represents the table public.permissions */
export default interface PermissionsTable {
	id: ColumnType<PermissionsId, PermissionsId | undefined, PermissionsId>;

	memberId: ColumnType<MembersId | null, MembersId | null, MembersId | null>;

	memberGroupId: ColumnType<MemberGroupsId | null, MemberGroupsId | null, MemberGroupsId | null>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Permissions = Selectable<PermissionsTable>;

export type NewPermissions = Insertable<PermissionsTable>;

export type PermissionsUpdate = Updateable<PermissionsTable>;
