// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type PermissionsId } from "./Permissions";
import { type PubsId } from "./Pubs";
import { type ColumnType, type Selectable, type Insertable, type Updateable } from "kysely";

/** Represents the table public._PermissionToPub */
export default interface PermissionToPubTable {
	A: ColumnType<PermissionsId, PermissionsId, PermissionsId>;

	B: ColumnType<PubsId, PubsId, PubsId>;
}

export type PermissionToPub = Selectable<PermissionToPubTable>;

export type NewPermissionToPub = Insertable<PermissionToPubTable>;

export type PermissionToPubUpdate = Updateable<PermissionToPubTable>;
