// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type PermissionsId } from "./Permissions";
import { type StagesId } from "./Stages";

/** Represents the table public._PermissionToStage */
export default interface PermissionToStageTable {
	A: ColumnType<PermissionsId, PermissionsId, PermissionsId>;

	B: ColumnType<StagesId, StagesId, StagesId>;
}

export type PermissionToStage = Selectable<PermissionToStageTable>;

export type NewPermissionToStage = Insertable<PermissionToStageTable>;

export type PermissionToStageUpdate = Updateable<PermissionToStageTable>;
