// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type default as CoreSchemaType } from "./CoreSchemaType";
import { type IntegrationsId } from "./Integrations";
import { type PubFieldSchemaId } from "./PubFieldSchema";

/** Identifier type for public.pub_fields */
export type PubFieldsId = string & { __brand: "PubFieldsId" };

/** Represents the table public.pub_fields */
export default interface PubFieldsTable {
	id: ColumnType<PubFieldsId, PubFieldsId | undefined, PubFieldsId>;

	name: ColumnType<string, string, string>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

	integrationId: ColumnType<IntegrationsId | null, IntegrationsId | null, IntegrationsId | null>;

	pubFieldSchemaId: ColumnType<
		PubFieldSchemaId | null,
		PubFieldSchemaId | null,
		PubFieldSchemaId | null
	>;

	slug: ColumnType<string, string, string>;

	schemaName: ColumnType<CoreSchemaType | null, CoreSchemaType | null, CoreSchemaType | null>;

	isArchived: ColumnType<boolean, boolean | undefined, boolean>;
}

export type PubFields = Selectable<PubFieldsTable>;

export type NewPubFields = Insertable<PubFieldsTable>;

export type PubFieldsUpdate = Updateable<PubFieldsTable>;
