// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type default as Action } from "./Action";
import { type IntegrationsId } from "./Integrations";
import { type PubFieldSchemaId } from "./PubFieldSchema";

/** Identifier type for public.pub_fields */
export type PubFieldsId = string & { __brand: "PubFieldsId" };

/** Represents the table public.pub_fields */
export default interface PubFieldsTable {
	id: ColumnType<PubFieldsId, PubFieldsId, PubFieldsId>;

	name: ColumnType<string, string, string>;

	created_at: ColumnType<Date, Date | string | undefined, Date | string>;

	updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

	integration_id: ColumnType<IntegrationsId | null, IntegrationsId | null, IntegrationsId | null>;

	pubFieldSchemaId: ColumnType<
		PubFieldSchemaId | null,
		PubFieldSchemaId | null,
		PubFieldSchemaId | null
	>;

	slug: ColumnType<string, string, string>;

	actions: ColumnType<Action[] | null, Action[] | null, Action[] | null>;
}

export type PubFields = Selectable<PubFieldsTable>;

export type NewPubFields = Insertable<PubFieldsTable>;

export type PubFieldsUpdate = Updateable<PubFieldsTable>;
