// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

/** Identifier type for public.PubFieldSchema */
export type PubFieldSchemaId = string & { __brand: "PubFieldSchemaId" };

/** Represents the table public.PubFieldSchema */
export default interface PubFieldSchemaTable {
	id: ColumnType<PubFieldSchemaId, PubFieldSchemaId | undefined, PubFieldSchemaId>;

	namespace: ColumnType<string, string, string>;

	name: ColumnType<string, string, string>;

	/** (JSONSchemaType<any>, 'ajv', true, false, true) */
	schema: ColumnType<unknown, unknown, unknown>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type PubFieldSchema = Selectable<PubFieldSchemaTable>;

export type NewPubFieldSchema = Insertable<PubFieldSchemaTable>;

export type PubFieldSchemaUpdate = Updateable<PubFieldSchemaTable>;
