// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type PubFieldsId } from './PubFields';
import { type PubsId } from './Pubs';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.pub_values */
export type PubValuesId = string & { __brand: 'PubValuesId' };

/** Represents the table public.pub_values */
export default interface PubValuesTable {
  id: ColumnType<PubValuesId, PubValuesId, PubValuesId>;

  field_id: ColumnType<PubFieldsId, PubFieldsId, PubFieldsId>;

  value: ColumnType<unknown, unknown, unknown>;

  pub_id: ColumnType<PubsId, PubsId, PubsId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type PubValues = Selectable<PubValuesTable>;

export type NewPubValues = Insertable<PubValuesTable>;

export type PubValuesUpdate = Updateable<PubValuesTable>;
