// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";

import { type CommunitiesId } from "./Communities";

/** Identifier type for public.stages */
export type StagesId = string & { __brand: "StagesId" };

/** Represents the table public.stages */
export default interface StagesTable {
	id: ColumnType<StagesId, StagesId | undefined, StagesId>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

	name: ColumnType<string, string, string>;

	order: ColumnType<string, string, string>;

	communityId: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>;
}

export type Stages = Selectable<StagesTable>;

export type NewStages = Insertable<StagesTable>;

export type StagesUpdate = Updateable<StagesTable>;
