// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CommunitiesId } from "./Communities";
import { type ColumnType, type Selectable, type Insertable, type Updateable } from "kysely";

/** Identifier type for public.stages */
export type StagesId = string & { __brand: "StagesId" };

/** Represents the table public.stages */
export default interface StagesTable {
	id: ColumnType<StagesId, StagesId, StagesId>;

	created_at: ColumnType<Date, Date | string | undefined, Date | string>;

	updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

	name: ColumnType<string, string, string>;

	order: ColumnType<string, string, string>;

	community_id: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>;
}

export type Stages = Selectable<StagesTable>;

export type NewStages = Insertable<StagesTable>;

export type StagesUpdate = Updateable<StagesTable>;
