// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface UsersTable {
<<<<<<< HEAD
	id: ColumnType<UsersId, UsersId | undefined, UsersId>;
=======
  id: ColumnType<UsersId, UsersId, UsersId>;
>>>>>>> a0252e8 (add schma and server actions)

  slug: ColumnType<string, string, string>;

  email: ColumnType<string, string, string>;

  firstName: ColumnType<string, string, string>;

  avatar: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  lastName: ColumnType<string | null, string | null, string | null>;

  orcid: ColumnType<string | null, string | null, string | null>;

  supabaseId: ColumnType<string | null, string | null, string | null>;

  isSuperAdmin: ColumnType<boolean, boolean | undefined, boolean>;
}

export type Users = Selectable<UsersTable>;

export type NewUsers = Insertable<UsersTable>;

export type UsersUpdate = Updateable<UsersTable>;
