# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
# Dependabot configuration file
# See documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    # package.json + pnpm catalog updates
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
      open-pull-requests-limit: 10
      labels:
          - "dependencies"
          - "npm"
      commit-message:
          prefix: "npm"
          include: "scope"
      # group all minor and patch updates together
      groups:
          minor-patch-dependencies:
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"

    # GitHub Actions updates
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
      open-pull-requests-limit: 5
      labels:
          - "dependencies"
          - "github-actions"
      commit-message:
          prefix: "github-actions"
          include: "scope"

    # docker updates
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
      open-pull-requests-limit: 5
      labels:
          - "dependencies"
          - "docker"
      commit-message:
          prefix: "docker"
          include: "scope"
