services:
    platform:
        environment:
            POSTGRES_USER: preview
            POSTGRES_PASSWORD: ${PREVIEW_POSTGRES_PASSWORD}
            POSTGRES_DB: preview
            MINIO_ROOT_USER: preview
            MINIO_ROOT_PASSWORD: ${PREVIEW_MINIO_ROOT_PASSWORD}
            ASSETS_UPLOAD_KEY: preview
            ASSETS_UPLOAD_SECRET_KEY: ${PREVIEW_ASSETS_UPLOAD_SECRET_KEY}
    seed:
        image: alpine:latest
        entrypoint: >
            /bin/sh -c '
            docker compose exec platform-migrations pnpm --filter core reset
            exit 0;
            '
        depends_on:
            platform-migrations:
                condition: service_completed_successfully
