services:
    platform:
        image: PLATFORM_IMAGE
        environment:
            POSTGRES_USER: preview
            POSTGRES_PASSWORD: preview
            POSTGRES_DB: preview
            MINIO_ROOT_USER: preview
            MINIO_ROOT_PASSWORD: preview
            ASSETS_UPLOAD_KEY: preview
            ASSETS_UPLOAD_SECRET_KEY: preview
            ASSETS_STORAGE_ENDPOINT: ${PULLPREVIEW_PUBLIC_DNS}/assets
    platform-jobs:
        image: JOBS_IMAGE
    platform-migrations:
        image: MIGRATIONS_IMAGE
        command:
            [
                "pnpm",
                "--filter",
                "core",
                "migrate-docker",
                "&&",
                "pnpm",
                "--filter",
                "core",
                "reset",
            ]
    caddy:
        image: caddy:latest
        depends_on:
            - platform
            - platform-jobs
            - minio
        env_file: .env
        ports:
            - "443:443"
        volumes:
            - ./self-host/caddy:/etc/caddy
            - caddy-data:/data
            - caddy-config:/config
        networks:
            - app-network
