services:
    platform:
        environment:
            POSTGRES_USER: preview
            POSTGRES_PASSWORD: preview
            POSTGRES_DB: preview
            MINIO_ROOT_USER: preview
            MINIO_ROOT_PASSWORD: preview
            ASSETS_UPLOAD_KEY: preview
            ASSETS_UPLOAD_SECRET_KEY: preview
