
# project node version
ARG NODE_VERSION=20.13.1

# package to be built
ARG PACKAGE

# port to expose the app on 
ARG PORT=3000

################################################################################
# Create the base image using node alpine
FROM node:${NODE_VERSION}-alpine as base

# pnpm version to install
ARG PNPM_VERSION=8.14.3

# Set working directory for all build stages.
WORKDIR /app

# Install pnpm.
RUN --mount=type=cache,target=/root/.npm \
    npm install -g pnpm@${PNPM_VERSION}

################################################################################
# Create a stage for building the application.
FROM base as build

# Beccause we use the alpine package we need to install postgres utilities for scripts
RUN apk add postgresql


# Copy the rest of the source files into the image.
COPY . .

# Run the build script.
RUN pnpm install --frozen-lockfile
RUN pnpm p:build

FROM build AS withpackage
ARG PACKAGE

RUN test -n "$PACKAGE" || (echo "PACKAGE  not set, required for this target" && false)

ENV DOCKERBUILD=1

RUN pnpm --filter $PACKAGE build && \
    pnpm --filter $PACKAGE --prod deploy /tmp/app && \
    pnpm --filter $PACKAGE exec \
      cp next.docker.config.js /tmp/app/next.config.js && \
    cp core/.env.docker /tmp/app/.env

# Necessary, perhaps, due to https://github.com/prisma/prisma/issues/15852
RUN if [[ ${PACKAGE} == core ]]; \
    then \
      find . -path '*/node_modules/.pnpm/@prisma+client*/node_modules/.prisma/client' \
      | xargs -r -I{} sh -c " \
        rm -rf /tmp/app/{} && \
        mkdir -p /tmp/app/{} && \
        cp -a {}/. /tmp/app/{}/" ; \
    fi

################################################################################
# Create a new stage to run the application with minimal runtime dependencies
# where the necessary files are copied from the build stage.
FROM base AS app
ARG PORT

# # needed so that the CMD can use this var
# ENV PACKAGE=$PACKAGE

# Use production node environment by default.
ENV NODE_ENV production

# Copy the deployed contents
COPY --from=withpackage /tmp/app \
     ./

# Run the application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE $PORT
# Run the application.
CMD pnpm start
