services:
    platform:
        environment:
            POSTGRES_USER: preview
            POSTGRES_PASSWORD: "${{ secrets.PREVIEW_POSTGRES_PASSWORD }}"
            POSTGRES_DB: preview
            MINIO_ROOT_USER: preview
            MINIO_ROOT_PASSWORD: "${{ secrets.PREVIEW_MINIO_ROOT_PASSWORD }}"
            ASSETS_UPLOAD_KEY: preview
            ASSETS_UPLOAD_SECRET_KEY: "${{ secrets.PREVIEW_ASSETS_UPLOAD_SECRET_KEY }}"
    seed:
        image: alpine:latest
        entrypoint: >
            /bin/sh -c '
            docker compose exec platform-migrations pnpm --filter core reset
            exit 0;
            '
        depends_on:
            platform-migrations:
                condition: service_completed_successfully
