FROM caddy:builder-alpine AS builder

RUN xcaddy build --with github.com/sagikazarmark/caddy-fs-s3

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]