services:
    platform:
        environment:
            POSTGRES_USER: preview
            POSTGRES_PASSWORD: preview
            POSTGRES_DB: preview
            MINIO_ROOT_USER: preview
            MINIO_ROOT_PASSWORD: preview
            ASSETS_UPLOAD_KEY: preview
            ASSETS_UPLOAD_SECRET_KEY: preview
    seed:
        platform: linux/amd64
        depends_on:
            db:
                condition: service_started
        image: ghcr.io/pubpub/platform-migrations:latest
        env_file: .env
        environment:
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        command: ["pnpm", "--filter", "core", "reset"]
        networks:
            - app-network
