packages:
    - "core"
    - "jobs"
    - "config/*"
    - "integrations/*"
    - "packages/*"
    - "storybook"

# A catalog is used to line up the package versions across workspaces
catalog:
    next: ^15.1.0
    eslint: ^9.9.0
    prettier: ^3.3.3
    tailwindcss: ^3.4.10
    tailwind-merge: ^2.5.2
    clsx: ^2.0.0
    postcss: ^8.4.27
    date-fns: ^4.1.0
    tsx: ^4.19.0
    typescript: 5.7.2
    zod: ^3.23.8
    react-hook-form: ^7.54.2
    "@hookform/resolvers": ^3.9.1
    "@sinclair/typebox": ^0.32.34
    "@types/node": ^20
    "@honeycombio/opentelemetry-node": ^0.6.1
    "@opentelemetry/auto-instrumentations-node": 0.53.0
    "@sentry/nextjs": "^8.47.0"
    "@ts-rest/core": 3.51.0
    "@ts-rest/next": 3.51.0
    "@ts-rest/open-api": 3.51.0
    "@ts-rest/serverless": 3.51.0
    "@ts-rest/react-query": 3.51.0

catalogs:
    react18:
        react: 18.3.1
        react-dom: 18.3.0
        "@types/react": ^18.3.5
        "@types/react-dom": ^18.3.0
    react19:
        react: ^19.0.0
        react-dom: ^19.0.0
        "@types/react": ^19.0.0
        "@types/react-dom": ^19.0.0
