packages:
    - "core"
    - "jobs"
    - "config/*"
    - "integrations/*"
    - "packages/*"

# A catalog is used to line up the package versions across workspaces
catalog:
    eslint: ^9.9.0
    prettier: ^3.3.3
    tailwindcss: ^3.4.10
    typescript: ^5.6.2

catalogs:
    react18:
        react: 18.3.1
        react-dom: 18.3.1
        "@types/react": ^18.3.3
        "@types/react-dom": ^18.3.0
