// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as PublicSchema } from "./public/PublicSchema";

/** We export this as named in order to avoid weirdness with preconstruct. */
export type Database = PublicSchema;

/** Backup default export that's the same as the above */
type DefaultDatabaseExport = PublicSchema;

export default DefaultDatabaseExport;
