// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { stagesIdSchema, type StagesId } from './Stages';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.move_constraint */
export default interface MoveConstraintTable {
  stageId: ColumnType<StagesId, StagesId, StagesId>;

  destinationId: ColumnType<StagesId, StagesId, StagesId>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type MoveConstraint = Selectable<MoveConstraintTable>;

export type NewMoveConstraint = Insertable<MoveConstraintTable>;

export type MoveConstraintUpdate = Updateable<MoveConstraintTable>;

export const moveConstraintSchema = z.object({
  stageId: stagesIdSchema,
  destinationId: stagesIdSchema,
  createdAt: z.date(),
  updatedAt: z.date(),
}) as z.ZodObject<{[K in keyof MoveConstraint]: z.Schema<MoveConstraint[K]>}>;

export const moveConstraintInitializerSchema = z.object({
  stageId: stagesIdSchema,
  destinationId: stagesIdSchema,
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
}) as z.ZodObject<{[K in keyof NewMoveConstraint]: z.Schema<NewMoveConstraint[K]>}>;

export const moveConstraintMutatorSchema = z.object({
  stageId: stagesIdSchema.optional(),
  destinationId: stagesIdSchema.optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
}) as z.ZodObject<{[K in keyof MoveConstraintUpdate]: z.Schema<MoveConstraintUpdate[K]>}>;
