// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { pubsIdSchema, type PubsId } from './Pubs';
import { stagesIdSchema, type StagesId } from './Stages';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.PubsInStages */
export default interface PubsInStagesTable {
  pubId: ColumnType<PubsId, PubsId, PubsId>;

  stageId: ColumnType<StagesId, StagesId, StagesId>;
}

export type PubsInStages = Selectable<PubsInStagesTable>;

export type NewPubsInStages = Insertable<PubsInStagesTable>;

export type PubsInStagesUpdate = Updateable<PubsInStagesTable>;

export const pubsInStagesSchema = z.object({
  pubId: pubsIdSchema,
  stageId: stagesIdSchema,
}) as z.ZodObject<{[K in keyof PubsInStages]: z.Schema<PubsInStages[K]>}>;

export const pubsInStagesInitializerSchema = z.object({
  pubId: pubsIdSchema,
  stageId: stagesIdSchema,
}) as z.ZodObject<{[K in keyof NewPubsInStages]: z.Schema<NewPubsInStages[K]>}>;

export const pubsInStagesMutatorSchema = z.object({
  pubId: pubsIdSchema.optional(),
  stageId: stagesIdSchema.optional(),
}) as z.ZodObject<{[K in keyof PubsInStagesUpdate]: z.Schema<PubsInStagesUpdate[K]>}>;
