apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: pubstar
    app.kubernetes.io/component: minio
spec:
  selector:
    app.kubernetes.io/component: minio
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
