apiVersion: v1
kind: Service
metadata:
  name: site-builder
  labels:
    app.kubernetes.io/name: pubstar
    app.kubernetes.io/component: site-builder
spec:
  selector:
    app.kubernetes.io/component: site-builder
  ports:
    - port: 4000
      targetPort: 4000
