apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pubstar-ingress
  labels:
    app.kubernetes.io/name: pubstar
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: sandbox.k3s.pubstar.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: sandbox-assets.k3s.pubstar.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
