apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/core.yaml
  - deployments/jobs.yaml
  - deployments/site-builder.yaml
  - statefulsets/postgres.yaml
  - statefulsets/valkey.yaml
  - statefulsets/minio.yaml
  - services/core.yaml
  - services/site-builder.yaml
  - services/postgres.yaml
  - services/valkey.yaml
  - services/minio.yaml
  - jobs/minio-init.yaml
  - configmaps/caddy-config.yaml
