// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod"

/** Represents the enum public.Action */
export enum Action {
	log = "log",
	email = "email",
	http = "http",
	move = "move",
	googleDriveImport = "googleDriveImport",
	datacite = "datacite",
	buildJournalSite = "buildJournalSite",
}

/** Zod schema for Action */
export const actionSchema = z.nativeEnum(Action)
