// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type Action, actionSchema } from "./Action"
import { type ActionInstancesId, actionInstancesIdSchema } from "./ActionInstances"
import { type ActionRunStatus, actionRunStatusSchema } from "./ActionRunStatus"
import { type AutomationEvent, automationEventSchema } from "./AutomationEvent"
import { type AutomationRunsId, automationRunsIdSchema } from "./AutomationRuns"
import { type PubsId, pubsIdSchema } from "./Pubs"
import { type UsersId, usersIdSchema } from "./Users"

/** Identifier type for public.action_runs */
export type ActionRunsId = string & { __brand: "ActionRunsId" }

/** Represents the table public.action_runs */
export interface ActionRunsTable {
	id: ColumnType<ActionRunsId, ActionRunsId | undefined, ActionRunsId>

	config: ColumnType<unknown | null, unknown | null, unknown | null>

	event: ColumnType<AutomationEvent | null, AutomationEvent | null, AutomationEvent | null>

	params: ColumnType<unknown | null, unknown | null, unknown | null>

	status: ColumnType<ActionRunStatus, ActionRunStatus, ActionRunStatus>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	result: ColumnType<unknown, unknown, unknown>

	json: ColumnType<unknown | null, unknown | null, unknown | null>

	action: ColumnType<Action | null, Action | null, Action | null>

	actionInstanceId: ColumnType<
		ActionInstancesId | null,
		ActionInstancesId | null,
		ActionInstancesId | null
	>

	automationRunId: ColumnType<
		AutomationRunsId | null,
		AutomationRunsId | null,
		AutomationRunsId | null
	>

	pubId: ColumnType<PubsId | null, PubsId | null, PubsId | null>

	userId: ColumnType<UsersId | null, UsersId | null, UsersId | null>
}

export type ActionRuns = Selectable<ActionRunsTable>

export type NewActionRuns = Insertable<ActionRunsTable>

export type ActionRunsUpdate = Updateable<ActionRunsTable>

export const actionRunsIdSchema = z.string().uuid() as unknown as z.Schema<ActionRunsId>

export const actionRunsSchema = z.object({
	id: actionRunsIdSchema,
	config: z.unknown().nullable(),
	event: automationEventSchema.nullable(),
	params: z.unknown().nullable(),
	status: actionRunStatusSchema,
	createdAt: z.date(),
	updatedAt: z.date(),
	result: z.unknown(),
	json: z.unknown().nullable(),
	action: actionSchema.nullable(),
	actionInstanceId: actionInstancesIdSchema.nullable(),
	automationRunId: automationRunsIdSchema.nullable(),
	pubId: pubsIdSchema.nullable(),
	userId: usersIdSchema.nullable(),
})

export const actionRunsInitializerSchema = z.object({
	id: actionRunsIdSchema.optional(),
	config: z.unknown().optional().nullable(),
	event: automationEventSchema.optional().nullable(),
	params: z.unknown().optional().nullable(),
	status: actionRunStatusSchema,
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	result: z.unknown(),
	json: z.unknown().optional().nullable(),
	action: actionSchema.optional().nullable(),
	actionInstanceId: actionInstancesIdSchema.optional().nullable(),
	automationRunId: automationRunsIdSchema.optional().nullable(),
	pubId: pubsIdSchema.optional().nullable(),
	userId: usersIdSchema.optional().nullable(),
})

export const actionRunsMutatorSchema = z.object({
	id: actionRunsIdSchema.optional(),
	config: z.unknown().optional().nullable(),
	event: automationEventSchema.optional().nullable(),
	params: z.unknown().optional().nullable(),
	status: actionRunStatusSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	result: z.unknown().optional(),
	json: z.unknown().optional().nullable(),
	action: actionSchema.optional().nullable(),
	actionInstanceId: actionInstancesIdSchema.optional().nullable(),
	automationRunId: automationRunsIdSchema.optional().nullable(),
	pubId: pubsIdSchema.optional().nullable(),
	userId: usersIdSchema.optional().nullable(),
})
