// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { ApiAccessPermissionConstraints } from "../types"

import { z } from "zod"

import { type ApiAccessScope, apiAccessScopeSchema } from "./ApiAccessScope"
import { type ApiAccessTokensId, apiAccessTokensIdSchema } from "./ApiAccessTokens"
import { type ApiAccessType, apiAccessTypeSchema } from "./ApiAccessType"

/** Identifier type for public.api_access_permissions */
export type ApiAccessPermissionsId = string & { __brand: "ApiAccessPermissionsId" }

/** Represents the table public.api_access_permissions */
export interface ApiAccessPermissionsTable {
	id: ColumnType<
		ApiAccessPermissionsId,
		ApiAccessPermissionsId | undefined,
		ApiAccessPermissionsId
	>

	scope: ColumnType<ApiAccessScope, ApiAccessScope, ApiAccessScope>

	accessType: ColumnType<ApiAccessType, ApiAccessType, ApiAccessType>

	constraints: ColumnType<
		ApiAccessPermissionConstraints | null,
		ApiAccessPermissionConstraints | null,
		ApiAccessPermissionConstraints | null
	>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	apiAccessTokenId: ColumnType<ApiAccessTokensId, ApiAccessTokensId, ApiAccessTokensId>
}

export type ApiAccessPermissions = Selectable<ApiAccessPermissionsTable>

export type NewApiAccessPermissions = Insertable<ApiAccessPermissionsTable>

export type ApiAccessPermissionsUpdate = Updateable<ApiAccessPermissionsTable>

export const apiAccessPermissionsIdSchema = z
	.string()
	.uuid() as unknown as z.Schema<ApiAccessPermissionsId>

export const apiAccessPermissionsSchema = z.object({
	id: apiAccessPermissionsIdSchema,
	scope: apiAccessScopeSchema,
	accessType: apiAccessTypeSchema,
	constraints: z.unknown().nullable(),
	createdAt: z.date(),
	updatedAt: z.date(),
	apiAccessTokenId: apiAccessTokensIdSchema,
})

export const apiAccessPermissionsInitializerSchema = z.object({
	id: apiAccessPermissionsIdSchema.optional(),
	scope: apiAccessScopeSchema,
	accessType: apiAccessTypeSchema,
	constraints: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	apiAccessTokenId: apiAccessTokensIdSchema,
})

export const apiAccessPermissionsMutatorSchema = z.object({
	id: apiAccessPermissionsIdSchema.optional(),
	scope: apiAccessScopeSchema.optional(),
	accessType: apiAccessTypeSchema.optional(),
	constraints: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	apiAccessTokenId: apiAccessTokensIdSchema.optional(),
})
