// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.ApiAccessTokenScopes */
enum ApiAccessTokenScope {
	community = "community",
	pub = "pub",
	stage = "stage",
	member = "member",
}

export default ApiAccessTokenScope;

/** Zod schema for ApiAccessTokenScopes */
export const apiAccessTokenScopesSchema = z.nativeEnum(ApiAccessTokenScope);
