// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type ApiAccessTokensId, apiAccessTokensIdSchema } from "./ApiAccessTokens"

/** Identifier type for public.api_access_logs */
export type ApiAccessLogsId = string & { __brand: "ApiAccessLogsId" }

/** Represents the table public.api_access_logs */
export interface ApiAccessLogsTable {
	id: ColumnType<ApiAccessLogsId, ApiAccessLogsId | undefined, ApiAccessLogsId>

	timestamp: ColumnType<Date, Date | string | undefined, Date | string>

	action: ColumnType<string, string, string>

	accessTokenId: ColumnType<
		ApiAccessTokensId | null,
		ApiAccessTokensId | null,
		ApiAccessTokensId | null
	>
}

export type ApiAccessLogs = Selectable<ApiAccessLogsTable>

export type NewApiAccessLogs = Insertable<ApiAccessLogsTable>

export type ApiAccessLogsUpdate = Updateable<ApiAccessLogsTable>

export const apiAccessLogsIdSchema = z.string().uuid() as unknown as z.Schema<ApiAccessLogsId>

export const apiAccessLogsSchema = z.object({
	id: apiAccessLogsIdSchema,
	timestamp: z.date(),
	action: z.string(),
	accessTokenId: apiAccessTokensIdSchema.nullable(),
})

export const apiAccessLogsInitializerSchema = z.object({
	id: apiAccessLogsIdSchema.optional(),
	timestamp: z.date().optional(),
	action: z.string(),
	accessTokenId: apiAccessTokensIdSchema.optional().nullable(),
})

export const apiAccessLogsMutatorSchema = z.object({
	id: apiAccessLogsIdSchema.optional(),
	timestamp: z.date().optional(),
	action: z.string().optional(),
	accessTokenId: apiAccessTokensIdSchema.optional().nullable(),
})
