// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type CommunitiesId, communitiesIdSchema } from "./Communities"
import { type UsersId, usersIdSchema } from "./Users"

/** Identifier type for public.api_access_tokens */
export type ApiAccessTokensId = string & { __brand: "ApiAccessTokensId" }

/** Represents the table public.api_access_tokens */
export interface ApiAccessTokensTable {
	id: ColumnType<ApiAccessTokensId, ApiAccessTokensId | undefined, ApiAccessTokensId>

	token: ColumnType<string, string, string>

	name: ColumnType<string, string, string>

	description: ColumnType<string | null, string | null, string | null>

	expiration: ColumnType<Date, Date | string, Date | string>

	issuedAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	isSiteBuilderToken: ColumnType<boolean, boolean | undefined, boolean>

	communityId: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>

	issuedById: ColumnType<UsersId | null, UsersId | null, UsersId | null>
}

export type ApiAccessTokens = Selectable<ApiAccessTokensTable>

export type NewApiAccessTokens = Insertable<ApiAccessTokensTable>

export type ApiAccessTokensUpdate = Updateable<ApiAccessTokensTable>

export const apiAccessTokensIdSchema = z.string().uuid() as unknown as z.Schema<ApiAccessTokensId>

export const apiAccessTokensSchema = z.object({
	id: apiAccessTokensIdSchema,
	token: z.string(),
	name: z.string(),
	description: z.string().nullable(),
	expiration: z.date(),
	issuedAt: z.date(),
	updatedAt: z.date(),
	isSiteBuilderToken: z.boolean(),
	communityId: communitiesIdSchema,
	issuedById: usersIdSchema.nullable(),
})

export const apiAccessTokensInitializerSchema = z.object({
	id: apiAccessTokensIdSchema.optional(),
	token: z.string(),
	name: z.string(),
	description: z.string().optional().nullable(),
	expiration: z.date(),
	issuedAt: z.date().optional(),
	updatedAt: z.date().optional(),
	isSiteBuilderToken: z.boolean().optional(),
	communityId: communitiesIdSchema,
	issuedById: usersIdSchema.optional().nullable(),
})

export const apiAccessTokensMutatorSchema = z.object({
	id: apiAccessTokensIdSchema.optional(),
	token: z.string().optional(),
	name: z.string().optional(),
	description: z.string().optional().nullable(),
	expiration: z.date().optional(),
	issuedAt: z.date().optional(),
	updatedAt: z.date().optional(),
	isSiteBuilderToken: z.boolean().optional(),
	communityId: communitiesIdSchema.optional(),
	issuedById: usersIdSchema.optional().nullable(),
})
