// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/**
 * Represents the enum public.AuthTokenType
 * @property generic - For most use-cases. This will just authenticate you with a regular session.
 * @property passwordReset - For resetting your password only
 * @property signup - For signing up, but also when you're invited to a community
 * @property verifyEmail - For verifying your email address
 */
export enum AuthTokenType {
	generic = "generic",
	passwordReset = "passwordReset",
	signup = "signup",
	verifyEmail = "verifyEmail",
}

/** Zod schema for AuthTokenType */
export const authTokenTypeSchema = z.nativeEnum(AuthTokenType);
