// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.AuthTokenType */
export enum AuthTokenType {
	magicLink = "magicLink",
	passwordReset = "passwordReset",
	signup = "signup",
	generic = "generic",
}

/** Zod schema for AuthTokenType */
export const authTokenTypeSchema = z.nativeEnum(AuthTokenType);
