// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.AutomationEvent */
export enum AutomationEvent {
	pubEnteredStage = "pubEnteredStage",
	pubLeftStage = "pubLeftStage",
	pubInStageForDuration = "pubInStageForDuration",
	automationSucceeded = "automationSucceeded",
	automationFailed = "automationFailed",
	webhook = "webhook",
	manual = "manual",
}

/** Zod schema for AutomationEvent */
export const automationEventSchema = z.nativeEnum(AutomationEvent);
