import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { AutomationsId } from "./Automations"

import { z } from "zod"

import { automationsIdSchema } from "./Automations"

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.AutomationRun */
export type AutomationRunId = string & { __brand: "AutomationRunId" }

/** Represents the table public.AutomationRun */
export interface AutomationRunTable {
	id: ColumnType<AutomationRunId, AutomationRunId | undefined, AutomationRunId>

	automationId: ColumnType<AutomationsId, AutomationsId, AutomationsId>

	config: ColumnType<unknown | null, unknown | null, unknown | null>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	sourceAutomationRunId: ColumnType<
		AutomationRunId | null,
		AutomationRunId | null,
		AutomationRunId | null
	>
}

export type AutomationRun = Selectable<AutomationRunTable>

export type NewAutomationRun = Insertable<AutomationRunTable>

export type AutomationRunUpdate = Updateable<AutomationRunTable>

export const automationRunIdSchema = z.string().uuid() as unknown as z.Schema<AutomationRunId>

export const automationRunSchema = z.object({
	id: automationRunIdSchema,
	automationId: automationsIdSchema,
	config: z.unknown().nullable(),
	createdAt: z.date(),
	updatedAt: z.date(),
	sourceAutomationRunId: automationRunIdSchema.nullable(),
})

export const automationRunInitializerSchema = z.object({
	id: automationRunIdSchema.optional(),
	automationId: automationsIdSchema,
	config: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	sourceAutomationRunId: automationRunIdSchema.optional().nullable(),
})

export const automationRunMutatorSchema = z.object({
	id: automationRunIdSchema.optional(),
	automationId: automationsIdSchema.optional(),
	config: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	sourceAutomationRunId: automationRunIdSchema.optional().nullable(),
})
