// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type AutomationEvent, automationEventSchema } from "./AutomationEvent"
import { type AutomationsId, automationsIdSchema } from "./Automations"
import { type UsersId, usersIdSchema } from "./Users"

/** Identifier type for public.automation_runs */
export type AutomationRunsId = string & { __brand: "AutomationRunsId" }

/** Represents the table public.automation_runs */
export interface AutomationRunsTable {
	id: ColumnType<AutomationRunsId, AutomationRunsId | undefined, AutomationRunsId>

	automationId: ColumnType<AutomationsId, AutomationsId, AutomationsId>

	event: ColumnType<AutomationEvent, AutomationEvent, AutomationEvent>

	config: ColumnType<unknown | null, unknown | null, unknown | null>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	sourceAutomationRunId: ColumnType<
		AutomationRunsId | null,
		AutomationRunsId | null,
		AutomationRunsId | null
	>

	userId: ColumnType<UsersId | null, UsersId | null, UsersId | null>
}

export type AutomationRuns = Selectable<AutomationRunsTable>

export type NewAutomationRuns = Insertable<AutomationRunsTable>

export type AutomationRunsUpdate = Updateable<AutomationRunsTable>

export const automationRunsIdSchema = z.string().uuid() as unknown as z.Schema<AutomationRunsId>

export const automationRunsSchema = z.object({
	id: automationRunsIdSchema,
	automationId: automationsIdSchema,
	event: automationEventSchema,
	config: z.unknown().nullable(),
	createdAt: z.date(),
	updatedAt: z.date(),
	sourceAutomationRunId: automationRunsIdSchema.nullable(),
	userId: usersIdSchema.nullable(),
})

export const automationRunsInitializerSchema = z.object({
	id: automationRunsIdSchema.optional(),
	automationId: automationsIdSchema,
	event: automationEventSchema,
	config: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	sourceAutomationRunId: automationRunsIdSchema.optional().nullable(),
	userId: usersIdSchema.optional().nullable(),
})

export const automationRunsMutatorSchema = z.object({
	id: automationRunsIdSchema.optional(),
	automationId: automationsIdSchema.optional(),
	event: automationEventSchema.optional(),
	config: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	sourceAutomationRunId: automationRunsIdSchema.optional().nullable(),
	userId: usersIdSchema.optional().nullable(),
})
