// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type AutomationEvent, automationEventSchema } from "./AutomationEvent"
import { type AutomationsId, automationsIdSchema } from "./Automations"
import { type PubsId, pubsIdSchema } from "./Pubs"
import { type UsersId, usersIdSchema } from "./Users"

/** Identifier type for public.automation_runs */
export type AutomationRunsId = string & { __brand: "AutomationRunsId" }

/** Represents the table public.automation_runs */
export interface AutomationRunsTable {
	id: ColumnType<AutomationRunsId, AutomationRunsId | undefined, AutomationRunsId>

	automationId: ColumnType<AutomationsId, AutomationsId, AutomationsId>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	sourceAutomationRunId: ColumnType<
		AutomationRunsId | null,
		AutomationRunsId | null,
		AutomationRunsId | null
	>

	inputJson: ColumnType<unknown, unknown, unknown>

	inputPubId: ColumnType<PubsId | null, PubsId | null, PubsId | null>

	sourceUserId: ColumnType<UsersId | null, UsersId | null, UsersId | null>

	triggerConfig: ColumnType<unknown | null, unknown | null, unknown | null>

	triggerEvent: ColumnType<AutomationEvent, AutomationEvent, AutomationEvent>
}

export type AutomationRuns = Selectable<AutomationRunsTable>

export type NewAutomationRuns = Insertable<AutomationRunsTable>

export type AutomationRunsUpdate = Updateable<AutomationRunsTable>

export const automationRunsIdSchema = z.string().uuid() as unknown as z.Schema<AutomationRunsId>

export const automationRunsSchema = z.object({
	id: automationRunsIdSchema,
	automationId: automationsIdSchema,
	createdAt: z.date(),
	updatedAt: z.date(),
	sourceAutomationRunId: automationRunsIdSchema.nullable(),
	inputJson: z.unknown(),
	inputPubId: pubsIdSchema.nullable(),
	sourceUserId: usersIdSchema.nullable(),
	triggerConfig: z.unknown().nullable(),
	triggerEvent: automationEventSchema,
})

export const automationRunsInitializerSchema = z.object({
	id: automationRunsIdSchema.optional(),
	automationId: automationsIdSchema,
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	sourceAutomationRunId: automationRunsIdSchema.optional().nullable(),
	inputJson: z.unknown(),
	inputPubId: pubsIdSchema.optional().nullable(),
	sourceUserId: usersIdSchema.optional().nullable(),
	triggerConfig: z.unknown().optional().nullable(),
	triggerEvent: automationEventSchema,
})

export const automationRunsMutatorSchema = z.object({
	id: automationRunsIdSchema.optional(),
	automationId: automationsIdSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	sourceAutomationRunId: automationRunsIdSchema.optional().nullable(),
	inputJson: z.unknown().optional(),
	inputPubId: pubsIdSchema.optional().nullable(),
	sourceUserId: usersIdSchema.optional().nullable(),
	triggerConfig: z.unknown().optional().nullable(),
	triggerEvent: automationEventSchema.optional(),
})
