// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { IconConfig } from "../types"

import { z } from "zod"

import { type CommunitiesId, communitiesIdSchema } from "./Communities"
import {
	type ConditionEvaluationTiming,
	conditionEvaluationTimingSchema,
} from "./ConditionEvaluationTiming"
import { type StagesId, stagesIdSchema } from "./Stages"

/** Identifier type for public.automations */
export type AutomationsId = string & { __brand: "AutomationsId" }

/** Represents the table public.automations */
export interface AutomationsTable {
	id: ColumnType<AutomationsId, AutomationsId | undefined, AutomationsId>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	conditionEvaluationTiming: ColumnType<
		ConditionEvaluationTiming | null,
		ConditionEvaluationTiming | null,
		ConditionEvaluationTiming | null
	>

	name: ColumnType<string, string, string>

	description: ColumnType<string | null, string | null, string | null>

	icon: ColumnType<IconConfig | null, IconConfig | null, IconConfig | null>

	stageId: ColumnType<StagesId | null, StagesId | null, StagesId | null>

	communityId: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>
}

export type Automations = Selectable<AutomationsTable>

export type NewAutomations = Insertable<AutomationsTable>

export type AutomationsUpdate = Updateable<AutomationsTable>

export const automationsIdSchema = z.string().uuid() as unknown as z.Schema<AutomationsId>

export const automationsSchema = z.object({
	id: automationsIdSchema,
	createdAt: z.date(),
	updatedAt: z.date(),
	conditionEvaluationTiming: conditionEvaluationTimingSchema.nullable(),
	name: z.string(),
	description: z.string().nullable(),
	icon: z.unknown().nullable(),
	stageId: stagesIdSchema.nullable(),
	communityId: communitiesIdSchema,
})

export const automationsInitializerSchema = z.object({
	id: automationsIdSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	conditionEvaluationTiming: conditionEvaluationTimingSchema.optional().nullable(),
	name: z.string(),
	description: z.string().optional().nullable(),
	icon: z.unknown().optional().nullable(),
	stageId: stagesIdSchema.optional().nullable(),
	communityId: communitiesIdSchema,
})

export const automationsMutatorSchema = z.object({
	id: automationsIdSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	conditionEvaluationTiming: conditionEvaluationTimingSchema.optional().nullable(),
	name: z.string().optional(),
	description: z.string().optional().nullable(),
	icon: z.unknown().optional().nullable(),
	stageId: stagesIdSchema.optional().nullable(),
	communityId: communitiesIdSchema.optional(),
})
