// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.AutomationConditionType */
export enum AutomationConditionType {
	jsonata = "jsonata",
}

/** Zod schema for AutomationConditionType */
export const automationConditionTypeSchema = z.nativeEnum(AutomationConditionType);
