// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import {
	type AutomationConditionBlockType,
	automationConditionBlockTypeSchema,
} from "./AutomationConditionBlockType"
import { type AutomationsId, automationsIdSchema } from "./Automations"

/** Identifier type for public.automation_condition_blocks */
export type AutomationConditionBlocksId = string & { __brand: "AutomationConditionBlocksId" }

/** Represents the table public.automation_condition_blocks */
export interface AutomationConditionBlocksTable {
	id: ColumnType<
		AutomationConditionBlocksId,
		AutomationConditionBlocksId | undefined,
		AutomationConditionBlocksId
	>

	type: ColumnType<
		AutomationConditionBlockType,
		AutomationConditionBlockType,
		AutomationConditionBlockType
	>

	rank: ColumnType<string, string, string>

	automationConditionBlockId: ColumnType<
		AutomationConditionBlocksId | null,
		AutomationConditionBlocksId | null,
		AutomationConditionBlocksId | null
	>

	automationId: ColumnType<AutomationsId, AutomationsId, AutomationsId>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>
}

export type AutomationConditionBlocks = Selectable<AutomationConditionBlocksTable>

export type NewAutomationConditionBlocks = Insertable<AutomationConditionBlocksTable>

export type AutomationConditionBlocksUpdate = Updateable<AutomationConditionBlocksTable>

export const automationConditionBlocksIdSchema = z
	.string()
	.uuid() as unknown as z.Schema<AutomationConditionBlocksId>

export const automationConditionBlocksSchema = z.object({
	id: automationConditionBlocksIdSchema,
	type: automationConditionBlockTypeSchema,
	rank: z.string(),
	automationConditionBlockId: automationConditionBlocksIdSchema.nullable(),
	automationId: automationsIdSchema,
	createdAt: z.date(),
	updatedAt: z.date(),
})

export const automationConditionBlocksInitializerSchema = z.object({
	id: automationConditionBlocksIdSchema.optional(),
	type: automationConditionBlockTypeSchema,
	rank: z.string(),
	automationConditionBlockId: automationConditionBlocksIdSchema.optional().nullable(),
	automationId: automationsIdSchema,
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
})

export const automationConditionBlocksMutatorSchema = z.object({
	id: automationConditionBlocksIdSchema.optional(),
	type: automationConditionBlockTypeSchema.optional(),
	rank: z.string().optional(),
	automationConditionBlockId: automationConditionBlocksIdSchema.optional().nullable(),
	automationId: automationsIdSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
})
