// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import {
	type AutomationConditionBlocksId,
	automationConditionBlocksIdSchema,
} from "./AutomationConditionBlocks"
import {
	type AutomationConditionType,
	automationConditionTypeSchema,
} from "./AutomationConditionType"

/** Identifier type for public.automation_conditions */
export type AutomationConditionsId = string & { __brand: "AutomationConditionsId" }

/** Represents the table public.automation_conditions */
export interface AutomationConditionsTable {
	id: ColumnType<
		AutomationConditionsId,
		AutomationConditionsId | undefined,
		AutomationConditionsId
	>

	rank: ColumnType<string, string, string>

	type: ColumnType<AutomationConditionType, AutomationConditionType, AutomationConditionType>

	expression: ColumnType<string, string, string>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	automationConditionBlockId: ColumnType<
		AutomationConditionBlocksId,
		AutomationConditionBlocksId,
		AutomationConditionBlocksId
	>
}

export type AutomationConditions = Selectable<AutomationConditionsTable>

export type NewAutomationConditions = Insertable<AutomationConditionsTable>

export type AutomationConditionsUpdate = Updateable<AutomationConditionsTable>

export const automationConditionsIdSchema = z
	.string()
	.uuid() as unknown as z.Schema<AutomationConditionsId>

export const automationConditionsSchema = z.object({
	id: automationConditionsIdSchema,
	rank: z.string(),
	type: automationConditionTypeSchema,
	expression: z.string(),
	createdAt: z.date(),
	updatedAt: z.date(),
	automationConditionBlockId: automationConditionBlocksIdSchema,
})

export const automationConditionsInitializerSchema = z.object({
	id: automationConditionsIdSchema.optional(),
	rank: z.string(),
	type: automationConditionTypeSchema,
	expression: z.string(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	automationConditionBlockId: automationConditionBlocksIdSchema,
})

export const automationConditionsMutatorSchema = z.object({
	id: automationConditionsIdSchema.optional(),
	rank: z.string().optional(),
	type: automationConditionTypeSchema.optional(),
	expression: z.string().optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	automationConditionBlockId: automationConditionBlocksIdSchema.optional(),
})
