// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type AutomationEvent, automationEventSchema } from "./AutomationEvent"
import { type AutomationsId, automationsIdSchema } from "./Automations"

/** Identifier type for public.automation_triggers */
export type AutomationTriggersId = string & { __brand: "AutomationTriggersId" }

/** Represents the table public.automation_triggers */
export interface AutomationTriggersTable {
	id: ColumnType<AutomationTriggersId, AutomationTriggersId | undefined, AutomationTriggersId>

	event: ColumnType<AutomationEvent, AutomationEvent, AutomationEvent>

	config: ColumnType<unknown | null, unknown | null, unknown | null>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	automationId: ColumnType<AutomationsId, AutomationsId, AutomationsId>

	sourceAutomationId: ColumnType<AutomationsId | null, AutomationsId | null, AutomationsId | null>
}

export type AutomationTriggers = Selectable<AutomationTriggersTable>

export type NewAutomationTriggers = Insertable<AutomationTriggersTable>

export type AutomationTriggersUpdate = Updateable<AutomationTriggersTable>

export const automationTriggersIdSchema = z
	.string()
	.uuid() as unknown as z.Schema<AutomationTriggersId>

export const automationTriggersSchema = z.object({
	id: automationTriggersIdSchema,
	event: automationEventSchema,
	config: z.unknown().nullable(),
	createdAt: z.date(),
	updatedAt: z.date(),
	automationId: automationsIdSchema,
	sourceAutomationId: automationsIdSchema.nullable(),
})

export const automationTriggersInitializerSchema = z.object({
	id: automationTriggersIdSchema.optional(),
	event: automationEventSchema,
	config: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	automationId: automationsIdSchema,
	sourceAutomationId: automationsIdSchema.optional().nullable(),
})

export const automationTriggersMutatorSchema = z.object({
	id: automationTriggersIdSchema.optional(),
	event: automationEventSchema.optional(),
	config: z.unknown().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	automationId: automationsIdSchema.optional(),
	sourceAutomationId: automationsIdSchema.optional().nullable(),
})
