// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.AutomationConditionBlockType */
export enum AutomationConditionBlockType {
	AND = "AND",
	OR = "OR",
	NOT = "NOT",
}

/** Zod schema for AutomationConditionBlockType */
export const automationConditionBlockTypeSchema = z.nativeEnum(AutomationConditionBlockType);
