import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import { z } from "zod";

import type { CommunitiesId } from "./Communities";
import type { PermissionsId } from "./Permissions";
import { communitiesIdSchema } from "./Communities";
import { permissionsIdSchema } from "./Permissions";

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public._CommunityToPermission */
export interface CommunityToPermissionTable {
	A: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>;

	B: ColumnType<PermissionsId, PermissionsId, PermissionsId>;
}

export type CommunityToPermission = Selectable<CommunityToPermissionTable>;

export type NewCommunityToPermission = Insertable<CommunityToPermissionTable>;

export type CommunityToPermissionUpdate = Updateable<CommunityToPermissionTable>;

export const communityToPermissionSchema = z.object({
	A: communitiesIdSchema,
	B: permissionsIdSchema,
});

export const communityToPermissionInitializerSchema = z.object({
	A: communitiesIdSchema,
	B: permissionsIdSchema,
});

export const communityToPermissionMutatorSchema = z.object({
	A: communitiesIdSchema.optional(),
	B: permissionsIdSchema.optional(),
});
