// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type CommunitiesId, communitiesIdSchema } from "./Communities"
import { type FormsId, formsIdSchema } from "./Forms"
import { type MemberGroupsId, memberGroupsIdSchema } from "./MemberGroups"
import { type MemberRole, memberRoleSchema } from "./MemberRole"
import { type UsersId, usersIdSchema } from "./Users"

/** Identifier type for public.community_memberships */
export type CommunityMembershipsId = string & { __brand: "CommunityMembershipsId" }

/** Represents the table public.community_memberships */
export interface CommunityMembershipsTable {
	id: ColumnType<
		CommunityMembershipsId,
		CommunityMembershipsId | undefined,
		CommunityMembershipsId
	>

	role: ColumnType<MemberRole, MemberRole, MemberRole>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	userId: ColumnType<UsersId | null, UsersId | null, UsersId | null>

	communityId: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>

	memberGroupId: ColumnType<MemberGroupsId | null, MemberGroupsId | null, MemberGroupsId | null>

	formId: ColumnType<FormsId | null, FormsId | null, FormsId | null>
}

export type CommunityMemberships = Selectable<CommunityMembershipsTable>

export type NewCommunityMemberships = Insertable<CommunityMembershipsTable>

export type CommunityMembershipsUpdate = Updateable<CommunityMembershipsTable>

export const communityMembershipsIdSchema = z
	.string()
	.uuid() as unknown as z.Schema<CommunityMembershipsId>

export const communityMembershipsSchema = z.object({
	id: communityMembershipsIdSchema,
	role: memberRoleSchema,
	createdAt: z.date(),
	updatedAt: z.date(),
	userId: usersIdSchema.nullable(),
	communityId: communitiesIdSchema,
	memberGroupId: memberGroupsIdSchema.nullable(),
	formId: formsIdSchema.nullable(),
})

export const communityMembershipsInitializerSchema = z.object({
	id: communityMembershipsIdSchema.optional(),
	role: memberRoleSchema,
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	userId: usersIdSchema.optional().nullable(),
	communityId: communitiesIdSchema,
	memberGroupId: memberGroupsIdSchema.optional().nullable(),
	formId: formsIdSchema.optional().nullable(),
})

export const communityMembershipsMutatorSchema = z.object({
	id: communityMembershipsIdSchema.optional(),
	role: memberRoleSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	userId: usersIdSchema.optional().nullable(),
	communityId: communitiesIdSchema.optional(),
	memberGroupId: memberGroupsIdSchema.optional().nullable(),
	formId: formsIdSchema.optional().nullable(),
})
