// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod"

/** Represents the enum public.ConditionEvaluationTiming */
export enum ConditionEvaluationTiming {
	onTrigger = "onTrigger",
	onExecution = "onExecution",
	both = "both",
}

/** Zod schema for ConditionEvaluationTiming */
export const conditionEvaluationTimingSchema = z.nativeEnum(ConditionEvaluationTiming)
