// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.CoreSchemaType */
export enum CoreSchemaType {
	Boolean = "Boolean",
	DateTime = "DateTime",
	Email = "Email",
	FileUpload = "FileUpload",
	MemberId = "MemberId",
	Null = "Null",
	Number = "Number",
	NumericArray = "NumericArray",
	String = "String",
	StringArray = "StringArray",
	URL = "URL",
	Vector3 = "Vector3",
	RichText = "RichText",
	ContextString = "ContextString",
}

/** Zod schema for CoreSchemaType */
export const coreSchemaTypeSchema = z.nativeEnum(CoreSchemaType);
