// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.ElementType */
export enum ElementType {
	pubfield = "pubfield",
	structural = "structural",
}

/** Zod schema for ElementType */
export const elementTypeSchema = z.nativeEnum(ElementType);
