// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod"

/** Represents the enum public.Event */
export enum Event {
	pubEnteredStage = "pubEnteredStage",
	pubLeftStage = "pubLeftStage",
	pubInStageForDuration = "pubInStageForDuration",
	actionSucceeded = "actionSucceeded",
	actionFailed = "actionFailed",
	webhook = "webhook",
}

/** Zod schema for Event */
export const eventSchema = z.nativeEnum(Event)
