import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import { z } from "zod";

import type { FormInputsId } from "./FormInputs";
import type { PubTypesId } from "./PubTypes";
import { formInputsIdSchema } from "./FormInputs";
import { pubTypesIdSchema } from "./PubTypes";

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public._FormInputToPubType */
export interface FormInputToPubTypeTable {
	A: ColumnType<FormInputsId, FormInputsId, FormInputsId>;

	B: ColumnType<PubTypesId, PubTypesId, PubTypesId>;
}

export type FormInputToPubType = Selectable<FormInputToPubTypeTable>;

export type NewFormInputToPubType = Insertable<FormInputToPubTypeTable>;

export type FormInputToPubTypeUpdate = Updateable<FormInputToPubTypeTable>;

export const formInputToPubTypeSchema = z.object({
	A: formInputsIdSchema,
	B: pubTypesIdSchema,
});

export const formInputToPubTypeInitializerSchema = z.object({
	A: formInputsIdSchema,
	B: pubTypesIdSchema,
});

export const formInputToPubTypeMutatorSchema = z.object({
	A: formInputsIdSchema.optional(),
	B: pubTypesIdSchema.optional(),
});
