// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod"

/** Represents the enum public.FormAccessType */
export enum FormAccessType {
	private = "private",
	inviteOnly = "inviteOnly",
	public = "public",
}

/** Zod schema for FormAccessType */
export const formAccessTypeSchema = z.nativeEnum(FormAccessType)
