import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import { z } from "zod";

import type { FormsId } from "./Forms";
import type { PermissionsId } from "./Permissions";
import { formsIdSchema } from "./Forms";
import { permissionsIdSchema } from "./Permissions";

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.form_to_permissions */
export interface FormToPermissionsTable {
	formId: ColumnType<FormsId, FormsId, FormsId>;

	permissionId: ColumnType<PermissionsId, PermissionsId, PermissionsId>;
}

export type FormToPermissions = Selectable<FormToPermissionsTable>;

export type NewFormToPermissions = Insertable<FormToPermissionsTable>;

export type FormToPermissionsUpdate = Updateable<FormToPermissionsTable>;

export const formToPermissionsSchema = z.object({
	formId: formsIdSchema,
	permissionId: permissionsIdSchema,
});

export const formToPermissionsInitializerSchema = z.object({
	formId: formsIdSchema,
	permissionId: permissionsIdSchema,
});

export const formToPermissionsMutatorSchema = z.object({
	formId: formsIdSchema.optional(),
	permissionId: permissionsIdSchema.optional(),
});
