import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";
import { z } from "zod";

import type { FormsId } from "./Forms";
import type { PermissionsId } from "./Permissions";
import { formsIdSchema } from "./Forms";
import { permissionsIdSchema } from "./Permissions";

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public._FormToPermission */
export interface FormToPermissionTable {
	A: ColumnType<FormsId, FormsId, FormsId>;

	B: ColumnType<PermissionsId, PermissionsId, PermissionsId>;
}

export type FormToPermission = Selectable<FormToPermissionTable>;

export type NewFormToPermission = Insertable<FormToPermissionTable>;

export type FormToPermissionUpdate = Updateable<FormToPermissionTable>;

export const formToPermissionSchema = z.object({
	A: formsIdSchema,
	B: permissionsIdSchema,
});

export const formToPermissionInitializerSchema = z.object({
	A: formsIdSchema,
	B: permissionsIdSchema,
});

export const formToPermissionMutatorSchema = z.object({
	A: formsIdSchema.optional(),
	B: permissionsIdSchema.optional(),
});
