import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import { z } from "zod";

import type { FormsId } from "./Forms";
import type { StructuralFormElement } from "./StructuralFormElement";
import { formsIdSchema } from "./Forms";
import { structuralFormElementSchema } from "./StructuralFormElement";

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.form_structural_elements */
export type FormStructuralElementsId = string & { __brand: "FormStructuralElementsId" };

/** Represents the table public.form_structural_elements */
export interface FormStructuralElementsTable {
	id: ColumnType<
		FormStructuralElementsId,
		FormStructuralElementsId | undefined,
		FormStructuralElementsId
	>;

	formId: ColumnType<FormsId, FormsId, FormsId>;

	rank: ColumnType<string, string, string>;

	element: ColumnType<StructuralFormElement, StructuralFormElement, StructuralFormElement>;

	content: ColumnType<string | null, string | null, string | null>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type FormStructuralElements = Selectable<FormStructuralElementsTable>;

export type NewFormStructuralElements = Insertable<FormStructuralElementsTable>;

export type FormStructuralElementsUpdate = Updateable<FormStructuralElementsTable>;

export const formStructuralElementsIdSchema = z
	.string()
	.uuid() as unknown as z.Schema<FormStructuralElementsId>;

export const formStructuralElementsSchema = z.object({
	id: formStructuralElementsIdSchema,
	formId: formsIdSchema,
	rank: z.string(),
	element: structuralFormElementSchema,
	content: z.string().nullable(),
	createdAt: z.date(),
	updatedAt: z.date(),
});

export const formStructuralElementsInitializerSchema = z.object({
	id: formStructuralElementsIdSchema.optional(),
	formId: formsIdSchema,
	rank: z.string(),
	element: structuralFormElementSchema,
	content: z.string().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
});

export const formStructuralElementsMutatorSchema = z.object({
	id: formStructuralElementsIdSchema.optional(),
	formId: formsIdSchema.optional(),
	rank: z.string().optional(),
	element: structuralFormElementSchema.optional(),
	content: z.string().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
});
