// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod"

/** Represents the enum public.InputComponent */
export enum InputComponent {
	textArea = "textArea",
	textInput = "textInput",
	datePicker = "datePicker",
	checkbox = "checkbox",
	fileUpload = "fileUpload",
	memberSelect = "memberSelect",
	confidenceInterval = "confidenceInterval",
	checkboxGroup = "checkboxGroup",
	radioGroup = "radioGroup",
	selectDropdown = "selectDropdown",
	multivalueInput = "multivalueInput",
	richText = "richText",
}

/** Zod schema for InputComponent */
export const inputComponentSchema = z.nativeEnum(InputComponent)
