// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { pubsIdSchema, type PubsId } from './Pubs';
import { integrationInstancesIdSchema, type IntegrationInstancesId } from './IntegrationInstances';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.IntegrationInstanceState */
export default interface IntegrationInstanceStateTable {
  pubId: ColumnType<PubsId, PubsId, PubsId>;

  instanceId: ColumnType<IntegrationInstancesId, IntegrationInstancesId, IntegrationInstancesId>;

  state: ColumnType<unknown, unknown, unknown>;
}

export type IntegrationInstanceState = Selectable<IntegrationInstanceStateTable>;

export type NewIntegrationInstanceState = Insertable<IntegrationInstanceStateTable>;

export type IntegrationInstanceStateUpdate = Updateable<IntegrationInstanceStateTable>;

export const integrationInstanceStateSchema = z.object({
  pubId: pubsIdSchema,
  instanceId: integrationInstancesIdSchema,
  state: z.unknown(),
}) satisfies z.Schema<IntegrationInstanceState>;

export const integrationInstanceStateInitializerSchema = z.object({
  pubId: pubsIdSchema,
  instanceId: integrationInstancesIdSchema,
  state: z.unknown(),
}) satisfies z.Schema<NewIntegrationInstanceState>;

export const integrationInstanceStateMutatorSchema = z.object({
  pubId: pubsIdSchema.optional(),
  instanceId: integrationInstancesIdSchema.optional(),
  state: z.unknown().optional(),
}) satisfies z.Schema<IntegrationInstanceStateUpdate>;
