// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the enum public.InviteStatus */
export enum InviteStatus {
	pending = "pending",
	accepted = "accepted",
	rejected = "rejected",
}

/** Zod schema for InviteStatus */
export const inviteStatusSchema = z.nativeEnum(InviteStatus);
