import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";
import { z } from "zod";

import type { CommunitiesId } from "./Communities";
import type { UsersId } from "./Users";
import { communitiesIdSchema } from "./Communities";
import { usersIdSchema } from "./Users";

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.members */
export type MembersId = string & { __brand: "MembersId" };

/** Represents the table public.members */
export default interface MembersTable {
	id: ColumnType<MembersId, MembersId | undefined, MembersId>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

	canAdmin: ColumnType<boolean, boolean, boolean>;

	communityId: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>;

	userId: ColumnType<UsersId, UsersId, UsersId>;
}

export type Members = Selectable<MembersTable>;

export type NewMembers = Insertable<MembersTable>;

export type MembersUpdate = Updateable<MembersTable>;

export const membersIdSchema = z.string().uuid() as unknown as z.Schema<MembersId>;

export const membersSchema = z.object({
	id: membersIdSchema,
	createdAt: z.date(),
	updatedAt: z.date(),
	canAdmin: z.boolean(),
	communityId: communitiesIdSchema,
	userId: usersIdSchema,
}) as z.ZodObject<{ [K in keyof Members]: z.Schema<Members[K]> }>;

export const membersInitializerSchema = z.object({
	id: membersIdSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	canAdmin: z.boolean(),
	communityId: communitiesIdSchema,
	userId: usersIdSchema,
}) as z.ZodObject<{ [K in keyof NewMembers]: z.Schema<NewMembers[K]> }>;

export const membersMutatorSchema = z.object({
	id: membersIdSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	canAdmin: z.boolean().optional(),
	communityId: communitiesIdSchema.optional(),
	userId: usersIdSchema.optional(),
}) as z.ZodObject<{ [K in keyof MembersUpdate]: z.Schema<MembersUpdate[K]> }>;
