// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the domain public.modified_by_type */
export type ModifiedByType = string;

/** Zod schema for modified_by_type */
export const modifiedByTypeSchema = z.string();
