// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod"

/** Represents the enum public.OperationType */
export enum OperationType {
	insert = "insert",
	update = "update",
	"delete" = "delete",
}

/** Zod schema for OperationType */
export const operationTypeSchema = z.nativeEnum(OperationType)
