// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { permissionsIdSchema, type PermissionsId } from './Permissions';
import { stagesIdSchema, type StagesId } from './Stages';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public._PermissionToStage */
export default interface PermissionToStageTable {
  A: ColumnType<PermissionsId, PermissionsId, PermissionsId>;

  B: ColumnType<StagesId, StagesId, StagesId>;
}

export type PermissionToStage = Selectable<PermissionToStageTable>;

export type NewPermissionToStage = Insertable<PermissionToStageTable>;

export type PermissionToStageUpdate = Updateable<PermissionToStageTable>;

export const permissionToStageSchema = z.object({
  A: permissionsIdSchema,
  B: stagesIdSchema,
}) as z.ZodObject<{[K in keyof PermissionToStage]: z.Schema<PermissionToStage[K]>}>;

export const permissionToStageInitializerSchema = z.object({
  A: permissionsIdSchema,
  B: stagesIdSchema,
}) as z.ZodObject<{[K in keyof NewPermissionToStage]: z.Schema<NewPermissionToStage[K]>}>;

export const permissionToStageMutatorSchema = z.object({
  A: permissionsIdSchema.optional(),
  B: stagesIdSchema.optional(),
}) as z.ZodObject<{[K in keyof PermissionToStageUpdate]: z.Schema<PermissionToStageUpdate[K]>}>;
