import { type ColumnType, type Insertable, type Selectable, type Updateable } from "kysely";
import { z } from "zod";

import type { PermissionsId } from "./Permissions";
import type { StagesId } from "./Stages";
import { permissionsIdSchema } from "./Permissions";
import { stagesIdSchema } from "./Stages";

// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public._PermissionToStage */
export default interface PermissionToStageTable {
	A: ColumnType<PermissionsId, PermissionsId, PermissionsId>;

	B: ColumnType<StagesId, StagesId, StagesId>;
}

export type PermissionToStage = Selectable<PermissionToStageTable>;

export type NewPermissionToStage = Insertable<PermissionToStageTable>;

export type PermissionToStageUpdate = Updateable<PermissionToStageTable>;

export const permissionToStageSchema = z.object({
	A: permissionsIdSchema,
	B: stagesIdSchema,
}) as z.ZodObject<{ [K in keyof PermissionToStage]: z.Schema<PermissionToStage[K]> }>;

export const permissionToStageInitializerSchema = z.object({
	A: permissionsIdSchema,
	B: stagesIdSchema,
}) as z.ZodObject<{ [K in keyof NewPermissionToStage]: z.Schema<NewPermissionToStage[K]> }>;

export const permissionToStageMutatorSchema = z.object({
	A: permissionsIdSchema.optional(),
	B: stagesIdSchema.optional(),
}) as z.ZodObject<{ [K in keyof PermissionToStageUpdate]: z.Schema<PermissionToStageUpdate[K]> }>;
