// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type CommunitiesId, communitiesIdSchema } from "./Communities"
import { type CoreSchemaType, coreSchemaTypeSchema } from "./CoreSchemaType"
import { type PubFieldSchemaId, pubFieldSchemaIdSchema } from "./PubFieldSchema"

/** Identifier type for public.pub_fields */
export type PubFieldsId = string & { __brand: "PubFieldsId" }

/** Represents the table public.pub_fields */
export interface PubFieldsTable {
	id: ColumnType<PubFieldsId, PubFieldsId | undefined, PubFieldsId>

	name: ColumnType<string, string, string>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	slug: ColumnType<string, string, string>

	schemaName: ColumnType<CoreSchemaType | null, CoreSchemaType | null, CoreSchemaType | null>

	isArchived: ColumnType<boolean, boolean | undefined, boolean>

	isRelation: ColumnType<boolean, boolean | undefined, boolean>

	communityId: ColumnType<CommunitiesId, CommunitiesId, CommunitiesId>

	pubFieldSchemaId: ColumnType<
		PubFieldSchemaId | null,
		PubFieldSchemaId | null,
		PubFieldSchemaId | null
	>
}

export type PubFields = Selectable<PubFieldsTable>

export type NewPubFields = Insertable<PubFieldsTable>

export type PubFieldsUpdate = Updateable<PubFieldsTable>

export const pubFieldsIdSchema = z.string().uuid() as unknown as z.Schema<PubFieldsId>

export const pubFieldsSchema = z.object({
	id: pubFieldsIdSchema,
	name: z.string(),
	createdAt: z.date(),
	updatedAt: z.date(),
	slug: z.string(),
	schemaName: coreSchemaTypeSchema.nullable(),
	isArchived: z.boolean(),
	isRelation: z.boolean(),
	communityId: communitiesIdSchema,
	pubFieldSchemaId: pubFieldSchemaIdSchema.nullable(),
})

export const pubFieldsInitializerSchema = z.object({
	id: pubFieldsIdSchema.optional(),
	name: z.string(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	slug: z.string(),
	schemaName: coreSchemaTypeSchema.optional().nullable(),
	isArchived: z.boolean().optional(),
	isRelation: z.boolean().optional(),
	communityId: communitiesIdSchema,
	pubFieldSchemaId: pubFieldSchemaIdSchema.optional().nullable(),
})

export const pubFieldsMutatorSchema = z.object({
	id: pubFieldsIdSchema.optional(),
	name: z.string().optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	slug: z.string().optional(),
	schemaName: coreSchemaTypeSchema.optional().nullable(),
	isArchived: z.boolean().optional(),
	isRelation: z.boolean().optional(),
	communityId: communitiesIdSchema.optional(),
	pubFieldSchemaId: pubFieldSchemaIdSchema.optional().nullable(),
})
