// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { pubFieldsIdSchema, type PubFieldsId } from './PubFields';
import { pubTypesIdSchema, type PubTypesId } from './PubTypes';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public._PubFieldToPubType */
export default interface PubFieldToPubTypeTable {
  A: ColumnType<PubFieldsId, PubFieldsId, PubFieldsId>;

  B: ColumnType<PubTypesId, PubTypesId, PubTypesId>;
}

export type PubFieldToPubType = Selectable<PubFieldToPubTypeTable>;

export type NewPubFieldToPubType = Insertable<PubFieldToPubTypeTable>;

export type PubFieldToPubTypeUpdate = Updateable<PubFieldToPubTypeTable>;

export const pubFieldToPubTypeSchema = z.object({
  A: pubFieldsIdSchema,
  B: pubTypesIdSchema,
}) as unknown as z.Schema<PubFieldToPubType>;

export const pubFieldToPubTypeInitializerSchema = z.object({
  A: pubFieldsIdSchema,
  B: pubTypesIdSchema,
}) satisfies z.Schema<NewPubFieldToPubType>;

export const pubFieldToPubTypeMutatorSchema = z.object({
  A: pubFieldsIdSchema.optional(),
  B: pubTypesIdSchema.optional(),
}) satisfies z.Schema<PubFieldToPubTypeUpdate>;
