// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActionConfigDefaultsTable } from "./ActionConfigDefaults";
import type { ActionInstancesTable } from "./ActionInstances";
import type { ActionRunsTable } from "./ActionRuns";
import type { ApiAccessLogsTable } from "./ApiAccessLogs";
import type { ApiAccessPermissionsTable } from "./ApiAccessPermissions";
import type { ApiAccessTokensTable } from "./ApiAccessTokens";
import type { AuthTokensTable } from "./AuthTokens";
import type { CommunitiesTable } from "./Communities";
import type { CommunityMembershipsTable } from "./CommunityMemberships";
import type { FormElementsTable } from "./FormElements";
import type { FormElementToPubTypeTable } from "./FormElementToPubType";
import type { FormsTable } from "./Forms";
import type { InviteFormsTable } from "./InviteForms";
import type { InvitesTable } from "./Invites";
import type { InvitesHistoryTable } from "./InvitesHistory";
import type { MemberGroupsTable } from "./MemberGroups";
import type { MemberGroupToUserTable } from "./MemberGroupToUser";
import type { MembershipCapabilitiesTable } from "./MembershipCapabilities";
import type { MoveConstraintTable } from "./MoveConstraint";
import type { PrismaMigrationsTable } from "./PrismaMigrations";
import type { PubFieldsTable } from "./PubFields";
import type { PubFieldSchemaTable } from "./PubFieldSchema";
import type { PubFieldToPubTypeTable } from "./PubFieldToPubType";
import type { PubMembershipsTable } from "./PubMemberships";
import type { PubsTable } from "./Pubs";
import type { PubsInStagesTable } from "./PubsInStages";
import type { PubTypesTable } from "./PubTypes";
import type { PubValuesTable } from "./PubValues";
import type { PubValuesHistoryTable } from "./PubValuesHistory";
import type { RulesTable } from "./Rules";
import type { SessionsTable } from "./Sessions";
import type { StageMembershipsTable } from "./StageMemberships";
import type { StagesTable } from "./Stages";
import type { UsersTable } from "./Users";

export interface PublicSchema {
	PubFieldSchema: PubFieldSchemaTable;

	membership_capabilities: MembershipCapabilitiesTable;

	sessions: SessionsTable;

	move_constraint: MoveConstraintTable;

	pub_values_history: PubValuesHistoryTable;

	api_access_tokens: ApiAccessTokensTable;

	_MemberGroupToUser: MemberGroupToUserTable;

	_FormElementToPubType: FormElementToPubTypeTable;

	PubsInStages: PubsInStagesTable;

	stage_memberships: StageMembershipsTable;

	rules: RulesTable;

	_prisma_migrations: PrismaMigrationsTable;

	auth_tokens: AuthTokensTable;

	api_access_permissions: ApiAccessPermissionsTable;

	api_access_logs: ApiAccessLogsTable;

	pub_types: PubTypesTable;

	pub_fields: PubFieldsTable;

	invites_history: InvitesHistoryTable;

	communities: CommunitiesTable;

	users: UsersTable;

	_PubFieldToPubType: PubFieldToPubTypeTable;

	pub_values: PubValuesTable;

	action_runs: ActionRunsTable;

	invites: InvitesTable;

	pubs: PubsTable;

	action_config_defaults: ActionConfigDefaultsTable;

	action_instances: ActionInstancesTable;

	community_memberships: CommunityMembershipsTable;

	member_groups: MemberGroupsTable;

	pub_memberships: PubMembershipsTable;

	stages: StagesTable;

	form_elements: FormElementsTable;

	forms: FormsTable;

	invite_forms: InviteFormsTable;
}
