// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActionConfigDefaultsTable } from "./ActionConfigDefaults"
import type { ActionInstancesTable } from "./ActionInstances"
import type { ActionRunsTable } from "./ActionRuns"
import type { ApiAccessLogsTable } from "./ApiAccessLogs"
import type { ApiAccessPermissionsTable } from "./ApiAccessPermissions"
import type { ApiAccessTokensTable } from "./ApiAccessTokens"
import type { AuthTokensTable } from "./AuthTokens"
import type { AutomationConditionBlocksTable } from "./AutomationConditionBlocks"
import type { AutomationConditionsTable } from "./AutomationConditions"
import type { AutomationRunsTable } from "./AutomationRuns"
import type { AutomationsTable } from "./Automations"
import type { AutomationTriggersTable } from "./AutomationTriggers"
import type { CommunitiesTable } from "./Communities"
import type { CommunityMembershipsTable } from "./CommunityMemberships"
import type { FormElementsTable } from "./FormElements"
import type { FormElementToPubTypeTable } from "./FormElementToPubType"
import type { FormsTable } from "./Forms"
import type { InviteFormsTable } from "./InviteForms"
import type { InvitesTable } from "./Invites"
import type { InvitesHistoryTable } from "./InvitesHistory"
import type { MemberGroupsTable } from "./MemberGroups"
import type { MemberGroupToUserTable } from "./MemberGroupToUser"
import type { MembershipCapabilitiesTable } from "./MembershipCapabilities"
import type { MoveConstraintTable } from "./MoveConstraint"
import type { PrismaMigrationsTable } from "./PrismaMigrations"
import type { PubFieldSchemaTable } from "./PubFieldSchema"
import type { PubFieldsTable } from "./PubFields"
import type { PubFieldToPubTypeTable } from "./PubFieldToPubType"
import type { PubMembershipsTable } from "./PubMemberships"
import type { PubsTable } from "./Pubs"
import type { PubsInStagesTable } from "./PubsInStages"
import type { PubTypesTable } from "./PubTypes"
import type { PubValuesTable } from "./PubValues"
import type { PubValuesHistoryTable } from "./PubValuesHistory"
import type { SessionsTable } from "./Sessions"
import type { StageMembershipsTable } from "./StageMemberships"
import type { StagesTable } from "./Stages"
import type { UsersTable } from "./Users"

export interface PublicSchema {
	PubFieldSchema: PubFieldSchemaTable

	automation_runs: AutomationRunsTable

	membership_capabilities: MembershipCapabilitiesTable

	sessions: SessionsTable

	move_constraint: MoveConstraintTable

	pub_values_history: PubValuesHistoryTable

	api_access_tokens: ApiAccessTokensTable

	_MemberGroupToUser: MemberGroupToUserTable

	PubsInStages: PubsInStagesTable

	_FormElementToPubType: FormElementToPubTypeTable

	stage_memberships: StageMembershipsTable

	_prisma_migrations: PrismaMigrationsTable

	auth_tokens: AuthTokensTable

	api_access_logs: ApiAccessLogsTable

	api_access_permissions: ApiAccessPermissionsTable

	pub_types: PubTypesTable

	automation_conditions: AutomationConditionsTable

	pub_fields: PubFieldsTable

	invites_history: InvitesHistoryTable

	communities: CommunitiesTable

	automation_triggers: AutomationTriggersTable

	users: UsersTable

	_PubFieldToPubType: PubFieldToPubTypeTable

	pub_values: PubValuesTable

	action_runs: ActionRunsTable

	pubs: PubsTable

	invites: InvitesTable

	action_instances: ActionInstancesTable

	action_config_defaults: ActionConfigDefaultsTable

	community_memberships: CommunityMembershipsTable

	member_groups: MemberGroupsTable

	pub_memberships: PubMembershipsTable

	stages: StagesTable

	automation_condition_blocks: AutomationConditionBlocksTable

	form_elements: FormElementsTable

	forms: FormsTable

	automations: AutomationsTable

	invite_forms: InviteFormsTable
}
