// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type FormsId, formsIdSchema } from "./Forms"
import { type MemberGroupsId, memberGroupsIdSchema } from "./MemberGroups"
import { type MemberRole, memberRoleSchema } from "./MemberRole"
import { type PubsId, pubsIdSchema } from "./Pubs"
import { type UsersId, usersIdSchema } from "./Users"

/** Identifier type for public.pub_memberships */
export type PubMembershipsId = string & { __brand: "PubMembershipsId" }

/** Represents the table public.pub_memberships */
export interface PubMembershipsTable {
	id: ColumnType<PubMembershipsId, PubMembershipsId | undefined, PubMembershipsId>

	role: ColumnType<MemberRole, MemberRole, MemberRole>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>

	userId: ColumnType<UsersId | null, UsersId | null, UsersId | null>

	pubId: ColumnType<PubsId, PubsId, PubsId>

	memberGroupId: ColumnType<MemberGroupsId | null, MemberGroupsId | null, MemberGroupsId | null>

	formId: ColumnType<FormsId | null, FormsId | null, FormsId | null>
}

export type PubMemberships = Selectable<PubMembershipsTable>

export type NewPubMemberships = Insertable<PubMembershipsTable>

export type PubMembershipsUpdate = Updateable<PubMembershipsTable>

export const pubMembershipsIdSchema = z.string().uuid() as unknown as z.Schema<PubMembershipsId>

export const pubMembershipsSchema = z.object({
	id: pubMembershipsIdSchema,
	role: memberRoleSchema,
	createdAt: z.date(),
	updatedAt: z.date(),
	userId: usersIdSchema.nullable(),
	pubId: pubsIdSchema,
	memberGroupId: memberGroupsIdSchema.nullable(),
	formId: formsIdSchema.nullable(),
})

export const pubMembershipsInitializerSchema = z.object({
	id: pubMembershipsIdSchema.optional(),
	role: memberRoleSchema,
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	userId: usersIdSchema.optional().nullable(),
	pubId: pubsIdSchema,
	memberGroupId: memberGroupsIdSchema.optional().nullable(),
	formId: formsIdSchema.optional().nullable(),
})

export const pubMembershipsMutatorSchema = z.object({
	id: pubMembershipsIdSchema.optional(),
	role: memberRoleSchema.optional(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
	userId: usersIdSchema.optional().nullable(),
	pubId: pubsIdSchema.optional(),
	memberGroupId: memberGroupsIdSchema.optional().nullable(),
	formId: formsIdSchema.optional().nullable(),
})
