// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { pubFieldsIdSchema, type PubFieldsId } from './PubFields';
import { pubsIdSchema, type PubsId } from './Pubs';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.pub_values */
export type PubValuesId = string & { __brand: 'PubValuesId' };

/** Represents the table public.pub_values */
export default interface PubValuesTable {
  id: ColumnType<PubValuesId, PubValuesId | undefined, PubValuesId>;

  fieldId: ColumnType<PubFieldsId, PubFieldsId, PubFieldsId>;

  value: ColumnType<unknown, unknown, unknown>;

  pubId: ColumnType<PubsId, PubsId, PubsId>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type PubValues = Selectable<PubValuesTable>;

export type NewPubValues = Insertable<PubValuesTable>;

export type PubValuesUpdate = Updateable<PubValuesTable>;

export const pubValuesIdSchema = z.string() as unknown as z.Schema<PubValuesId>;

export const pubValuesSchema = z.object({
  id: pubValuesIdSchema,
  fieldId: pubFieldsIdSchema,
  value: z.unknown(),
  pubId: pubsIdSchema,
  createdAt: z.date(),
  updatedAt: z.date(),
}) as unknown as z.Schema<PubValues>;

export const pubValuesInitializerSchema = z.object({
  id: pubValuesIdSchema.optional(),
  fieldId: pubFieldsIdSchema,
  value: z.unknown(),
  pubId: pubsIdSchema,
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
}) satisfies z.Schema<NewPubValues>;

export const pubValuesMutatorSchema = z.object({
  id: pubValuesIdSchema.optional(),
  fieldId: pubFieldsIdSchema.optional(),
  value: z.unknown().optional(),
  pubId: pubsIdSchema.optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
}) satisfies z.Schema<PubValuesUpdate>;
