// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the domain public.slug */
export type Slug = string;

/** Zod schema for slug */
export const slugSchema = z.string();
